### ISSUE TITLE
Some improvments

### ISSUE THREAD

**Issue by murashki** [thesabbir/simple-line-icons#15]
#### One

```html
<span class="icons-logout"> Log out me!</span>
```

This feature need css like:
```css
*[class^="icons-"] {
  font-family: inherit;
}
*[class^="icons-"]:before {
  font-family: 'Simple-Line-Icons';
}
```

Anyway, there is not need to have all `span` under the `Simple-Line-Icons` font. It's enough to have `font-family` style only for icon (ie `:before`). Thus we could use outer font inside the `span`.

#### Two
It's would be nice if css names were: `.icons-gameController`, not `.icons-game-controller`. Cause of `-` is significant character in css, and used for some logic, not for words separator. It's a more right way IMO to use `_` or camelCase, but not `-`.

https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors
```
[attr|=value]
Represents an element with an attribute name of attr. Its value can be exactly “value” or can begin with “value” immediately followed by “-” (U+002D). It can be used for language subcode matches.
```

Thanks for icons! It's amazing!
